//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: ibc/core/channel/v1/tx.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Msg defines the ibc/channel Msg service.
///
/// Usage: instantiate `Ibc_Core_Channel_V1_MsgClient`, then call methods of this protocol to make API calls.
internal protocol Ibc_Core_Channel_V1_MsgClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Ibc_Core_Channel_V1_MsgClientInterceptorFactoryProtocol? { get }

  func channelOpenInit(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenInit,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenInit, Ibc_Core_Channel_V1_MsgChannelOpenInitResponse>

  func channelOpenTry(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenTry,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenTry, Ibc_Core_Channel_V1_MsgChannelOpenTryResponse>

  func channelOpenAck(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenAck,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenAck, Ibc_Core_Channel_V1_MsgChannelOpenAckResponse>

  func channelOpenConfirm(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenConfirm,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenConfirm, Ibc_Core_Channel_V1_MsgChannelOpenConfirmResponse>

  func channelCloseInit(
    _ request: Ibc_Core_Channel_V1_MsgChannelCloseInit,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelCloseInit, Ibc_Core_Channel_V1_MsgChannelCloseInitResponse>

  func channelCloseConfirm(
    _ request: Ibc_Core_Channel_V1_MsgChannelCloseConfirm,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelCloseConfirm, Ibc_Core_Channel_V1_MsgChannelCloseConfirmResponse>

  func recvPacket(
    _ request: Ibc_Core_Channel_V1_MsgRecvPacket,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgRecvPacket, Ibc_Core_Channel_V1_MsgRecvPacketResponse>

  func timeout(
    _ request: Ibc_Core_Channel_V1_MsgTimeout,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgTimeout, Ibc_Core_Channel_V1_MsgTimeoutResponse>

  func timeoutOnClose(
    _ request: Ibc_Core_Channel_V1_MsgTimeoutOnClose,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgTimeoutOnClose, Ibc_Core_Channel_V1_MsgTimeoutOnCloseResponse>

  func acknowledgement(
    _ request: Ibc_Core_Channel_V1_MsgAcknowledgement,
    callOptions: CallOptions?
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgAcknowledgement, Ibc_Core_Channel_V1_MsgAcknowledgementResponse>
}

extension Ibc_Core_Channel_V1_MsgClientProtocol {
  internal var serviceName: String {
    return "ibc.core.channel.v1.Msg"
  }

  /// ChannelOpenInit defines a rpc handler method for MsgChannelOpenInit.
  ///
  /// - Parameters:
  ///   - request: Request to send to ChannelOpenInit.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func channelOpenInit(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenInit,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenInit, Ibc_Core_Channel_V1_MsgChannelOpenInitResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/ChannelOpenInit",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChannelOpenInitInterceptors() ?? []
    )
  }

  /// ChannelOpenTry defines a rpc handler method for MsgChannelOpenTry.
  ///
  /// - Parameters:
  ///   - request: Request to send to ChannelOpenTry.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func channelOpenTry(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenTry,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenTry, Ibc_Core_Channel_V1_MsgChannelOpenTryResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/ChannelOpenTry",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChannelOpenTryInterceptors() ?? []
    )
  }

  /// ChannelOpenAck defines a rpc handler method for MsgChannelOpenAck.
  ///
  /// - Parameters:
  ///   - request: Request to send to ChannelOpenAck.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func channelOpenAck(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenAck,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenAck, Ibc_Core_Channel_V1_MsgChannelOpenAckResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/ChannelOpenAck",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChannelOpenAckInterceptors() ?? []
    )
  }

  /// ChannelOpenConfirm defines a rpc handler method for MsgChannelOpenConfirm.
  ///
  /// - Parameters:
  ///   - request: Request to send to ChannelOpenConfirm.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func channelOpenConfirm(
    _ request: Ibc_Core_Channel_V1_MsgChannelOpenConfirm,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelOpenConfirm, Ibc_Core_Channel_V1_MsgChannelOpenConfirmResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/ChannelOpenConfirm",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChannelOpenConfirmInterceptors() ?? []
    )
  }

  /// ChannelCloseInit defines a rpc handler method for MsgChannelCloseInit.
  ///
  /// - Parameters:
  ///   - request: Request to send to ChannelCloseInit.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func channelCloseInit(
    _ request: Ibc_Core_Channel_V1_MsgChannelCloseInit,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelCloseInit, Ibc_Core_Channel_V1_MsgChannelCloseInitResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/ChannelCloseInit",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChannelCloseInitInterceptors() ?? []
    )
  }

  /// ChannelCloseConfirm defines a rpc handler method for MsgChannelCloseConfirm.
  ///
  /// - Parameters:
  ///   - request: Request to send to ChannelCloseConfirm.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func channelCloseConfirm(
    _ request: Ibc_Core_Channel_V1_MsgChannelCloseConfirm,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgChannelCloseConfirm, Ibc_Core_Channel_V1_MsgChannelCloseConfirmResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/ChannelCloseConfirm",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeChannelCloseConfirmInterceptors() ?? []
    )
  }

  /// RecvPacket defines a rpc handler method for MsgRecvPacket.
  ///
  /// - Parameters:
  ///   - request: Request to send to RecvPacket.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func recvPacket(
    _ request: Ibc_Core_Channel_V1_MsgRecvPacket,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgRecvPacket, Ibc_Core_Channel_V1_MsgRecvPacketResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/RecvPacket",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRecvPacketInterceptors() ?? []
    )
  }

  /// Timeout defines a rpc handler method for MsgTimeout.
  ///
  /// - Parameters:
  ///   - request: Request to send to Timeout.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func timeout(
    _ request: Ibc_Core_Channel_V1_MsgTimeout,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgTimeout, Ibc_Core_Channel_V1_MsgTimeoutResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/Timeout",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTimeoutInterceptors() ?? []
    )
  }

  /// TimeoutOnClose defines a rpc handler method for MsgTimeoutOnClose.
  ///
  /// - Parameters:
  ///   - request: Request to send to TimeoutOnClose.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func timeoutOnClose(
    _ request: Ibc_Core_Channel_V1_MsgTimeoutOnClose,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgTimeoutOnClose, Ibc_Core_Channel_V1_MsgTimeoutOnCloseResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/TimeoutOnClose",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTimeoutOnCloseInterceptors() ?? []
    )
  }

  /// Acknowledgement defines a rpc handler method for MsgAcknowledgement.
  ///
  /// - Parameters:
  ///   - request: Request to send to Acknowledgement.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func acknowledgement(
    _ request: Ibc_Core_Channel_V1_MsgAcknowledgement,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Ibc_Core_Channel_V1_MsgAcknowledgement, Ibc_Core_Channel_V1_MsgAcknowledgementResponse> {
    return self.makeUnaryCall(
      path: "/ibc.core.channel.v1.Msg/Acknowledgement",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAcknowledgementInterceptors() ?? []
    )
  }
}

internal protocol Ibc_Core_Channel_V1_MsgClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'channelOpenInit'.
  func makeChannelOpenInitInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgChannelOpenInit, Ibc_Core_Channel_V1_MsgChannelOpenInitResponse>]

  /// - Returns: Interceptors to use when invoking 'channelOpenTry'.
  func makeChannelOpenTryInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgChannelOpenTry, Ibc_Core_Channel_V1_MsgChannelOpenTryResponse>]

  /// - Returns: Interceptors to use when invoking 'channelOpenAck'.
  func makeChannelOpenAckInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgChannelOpenAck, Ibc_Core_Channel_V1_MsgChannelOpenAckResponse>]

  /// - Returns: Interceptors to use when invoking 'channelOpenConfirm'.
  func makeChannelOpenConfirmInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgChannelOpenConfirm, Ibc_Core_Channel_V1_MsgChannelOpenConfirmResponse>]

  /// - Returns: Interceptors to use when invoking 'channelCloseInit'.
  func makeChannelCloseInitInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgChannelCloseInit, Ibc_Core_Channel_V1_MsgChannelCloseInitResponse>]

  /// - Returns: Interceptors to use when invoking 'channelCloseConfirm'.
  func makeChannelCloseConfirmInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgChannelCloseConfirm, Ibc_Core_Channel_V1_MsgChannelCloseConfirmResponse>]

  /// - Returns: Interceptors to use when invoking 'recvPacket'.
  func makeRecvPacketInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgRecvPacket, Ibc_Core_Channel_V1_MsgRecvPacketResponse>]

  /// - Returns: Interceptors to use when invoking 'timeout'.
  func makeTimeoutInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgTimeout, Ibc_Core_Channel_V1_MsgTimeoutResponse>]

  /// - Returns: Interceptors to use when invoking 'timeoutOnClose'.
  func makeTimeoutOnCloseInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgTimeoutOnClose, Ibc_Core_Channel_V1_MsgTimeoutOnCloseResponse>]

  /// - Returns: Interceptors to use when invoking 'acknowledgement'.
  func makeAcknowledgementInterceptors() -> [ClientInterceptor<Ibc_Core_Channel_V1_MsgAcknowledgement, Ibc_Core_Channel_V1_MsgAcknowledgementResponse>]
}

internal final class Ibc_Core_Channel_V1_MsgClient: Ibc_Core_Channel_V1_MsgClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Ibc_Core_Channel_V1_MsgClientInterceptorFactoryProtocol?

  /// Creates a client for the ibc.core.channel.v1.Msg service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Ibc_Core_Channel_V1_MsgClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

