//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: provenance/metadata/v0/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Query defines the Metadata Query service.
///
/// Usage: instantiate `Query_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Query_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Query_QueryClientInterceptorFactoryProtocol? { get }

  func scope(
    _ request: Query_ScopeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Query_ScopeRequest, Query_ScopeResponse>
}

extension Query_QueryClientProtocol {
  internal var serviceName: String {
    return "query.Query"
  }

  /// Scope returns a specific scope by id
  ///
  /// - Parameters:
  ///   - request: Request to send to Scope.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func scope(
    _ request: Query_ScopeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Query_ScopeRequest, Query_ScopeResponse> {
    return self.makeUnaryCall(
      path: "/query.Query/Scope",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeScopeInterceptors() ?? []
    )
  }
}

internal protocol Query_QueryClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'scope'.
  func makeScopeInterceptors() -> [ClientInterceptor<Query_ScopeRequest, Query_ScopeResponse>]
}

internal final class Query_QueryClient: Query_QueryClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Query_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the query.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Query_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

