//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: x/wasm/internal/types/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Query provides defines the gRPC querier service
///
/// Usage: instantiate `Cosmwasm_Wasm_V1beta1_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Cosmwasm_Wasm_V1beta1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Cosmwasm_Wasm_V1beta1_QueryClientInterceptorFactoryProtocol? { get }

  func contractInfo(
    _ request: Cosmwasm_Wasm_V1beta1_QueryContractInfoRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryContractInfoRequest, Cosmwasm_Wasm_V1beta1_QueryContractInfoResponse>

  func contractHistory(
    _ request: Cosmwasm_Wasm_V1beta1_QueryContractHistoryRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryContractHistoryRequest, Cosmwasm_Wasm_V1beta1_QueryContractHistoryResponse>

  func contractsByCode(
    _ request: Cosmwasm_Wasm_V1beta1_QueryContractsByCodeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryContractsByCodeRequest, Cosmwasm_Wasm_V1beta1_QueryContractsByCodeResponse>

  func allContractState(
    _ request: Cosmwasm_Wasm_V1beta1_QueryAllContractStateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryAllContractStateRequest, Cosmwasm_Wasm_V1beta1_QueryAllContractStateResponse>

  func rawContractState(
    _ request: Cosmwasm_Wasm_V1beta1_QueryRawContractStateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryRawContractStateRequest, Cosmwasm_Wasm_V1beta1_QueryRawContractStateResponse>

  func smartContractState(
    _ request: Cosmwasm_Wasm_V1beta1_QuerySmartContractStateRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QuerySmartContractStateRequest, Cosmwasm_Wasm_V1beta1_QuerySmartContractStateResponse>

  func code(
    _ request: Cosmwasm_Wasm_V1beta1_QueryCodeRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryCodeRequest, Cosmwasm_Wasm_V1beta1_QueryCodeResponse>

  func codes(
    _ request: Cosmwasm_Wasm_V1beta1_QueryCodesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryCodesRequest, Cosmwasm_Wasm_V1beta1_QueryCodesResponse>
}

extension Cosmwasm_Wasm_V1beta1_QueryClientProtocol {
  internal var serviceName: String {
    return "cosmwasm.wasm.v1beta1.Query"
  }

  /// ContractInfo gets the contract meta data
  ///
  /// - Parameters:
  ///   - request: Request to send to ContractInfo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func contractInfo(
    _ request: Cosmwasm_Wasm_V1beta1_QueryContractInfoRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryContractInfoRequest, Cosmwasm_Wasm_V1beta1_QueryContractInfoResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/ContractInfo",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeContractInfoInterceptors() ?? []
    )
  }

  /// ContractHistory gets the contract code history
  ///
  /// - Parameters:
  ///   - request: Request to send to ContractHistory.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func contractHistory(
    _ request: Cosmwasm_Wasm_V1beta1_QueryContractHistoryRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryContractHistoryRequest, Cosmwasm_Wasm_V1beta1_QueryContractHistoryResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/ContractHistory",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeContractHistoryInterceptors() ?? []
    )
  }

  /// ContractsByCode lists all smart contracts for a code id
  ///
  /// - Parameters:
  ///   - request: Request to send to ContractsByCode.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func contractsByCode(
    _ request: Cosmwasm_Wasm_V1beta1_QueryContractsByCodeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryContractsByCodeRequest, Cosmwasm_Wasm_V1beta1_QueryContractsByCodeResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/ContractsByCode",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeContractsByCodeInterceptors() ?? []
    )
  }

  /// AllContractState gets all raw store data for a single contract
  ///
  /// - Parameters:
  ///   - request: Request to send to AllContractState.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func allContractState(
    _ request: Cosmwasm_Wasm_V1beta1_QueryAllContractStateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryAllContractStateRequest, Cosmwasm_Wasm_V1beta1_QueryAllContractStateResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/AllContractState",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeAllContractStateInterceptors() ?? []
    )
  }

  /// RawContractState gets single key from the raw store data of a contract
  ///
  /// - Parameters:
  ///   - request: Request to send to RawContractState.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func rawContractState(
    _ request: Cosmwasm_Wasm_V1beta1_QueryRawContractStateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryRawContractStateRequest, Cosmwasm_Wasm_V1beta1_QueryRawContractStateResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/RawContractState",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRawContractStateInterceptors() ?? []
    )
  }

  /// SmartContractState get smart query result from the contract
  ///
  /// - Parameters:
  ///   - request: Request to send to SmartContractState.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func smartContractState(
    _ request: Cosmwasm_Wasm_V1beta1_QuerySmartContractStateRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QuerySmartContractStateRequest, Cosmwasm_Wasm_V1beta1_QuerySmartContractStateResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/SmartContractState",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSmartContractStateInterceptors() ?? []
    )
  }

  /// Code gets the binary code and metadata for a singe wasm code
  ///
  /// - Parameters:
  ///   - request: Request to send to Code.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func code(
    _ request: Cosmwasm_Wasm_V1beta1_QueryCodeRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryCodeRequest, Cosmwasm_Wasm_V1beta1_QueryCodeResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/Code",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCodeInterceptors() ?? []
    )
  }

  /// Codes gets the metadata for all stored wasm codes
  ///
  /// - Parameters:
  ///   - request: Request to send to Codes.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func codes(
    _ request: Cosmwasm_Wasm_V1beta1_QueryCodesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Cosmwasm_Wasm_V1beta1_QueryCodesRequest, Cosmwasm_Wasm_V1beta1_QueryCodesResponse> {
    return self.makeUnaryCall(
      path: "/cosmwasm.wasm.v1beta1.Query/Codes",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCodesInterceptors() ?? []
    )
  }
}

internal protocol Cosmwasm_Wasm_V1beta1_QueryClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'contractInfo'.
  func makeContractInfoInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QueryContractInfoRequest, Cosmwasm_Wasm_V1beta1_QueryContractInfoResponse>]

  /// - Returns: Interceptors to use when invoking 'contractHistory'.
  func makeContractHistoryInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QueryContractHistoryRequest, Cosmwasm_Wasm_V1beta1_QueryContractHistoryResponse>]

  /// - Returns: Interceptors to use when invoking 'contractsByCode'.
  func makeContractsByCodeInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QueryContractsByCodeRequest, Cosmwasm_Wasm_V1beta1_QueryContractsByCodeResponse>]

  /// - Returns: Interceptors to use when invoking 'allContractState'.
  func makeAllContractStateInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QueryAllContractStateRequest, Cosmwasm_Wasm_V1beta1_QueryAllContractStateResponse>]

  /// - Returns: Interceptors to use when invoking 'rawContractState'.
  func makeRawContractStateInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QueryRawContractStateRequest, Cosmwasm_Wasm_V1beta1_QueryRawContractStateResponse>]

  /// - Returns: Interceptors to use when invoking 'smartContractState'.
  func makeSmartContractStateInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QuerySmartContractStateRequest, Cosmwasm_Wasm_V1beta1_QuerySmartContractStateResponse>]

  /// - Returns: Interceptors to use when invoking 'code'.
  func makeCodeInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QueryCodeRequest, Cosmwasm_Wasm_V1beta1_QueryCodeResponse>]

  /// - Returns: Interceptors to use when invoking 'codes'.
  func makeCodesInterceptors() -> [ClientInterceptor<Cosmwasm_Wasm_V1beta1_QueryCodesRequest, Cosmwasm_Wasm_V1beta1_QueryCodesResponse>]
}

internal final class Cosmwasm_Wasm_V1beta1_QueryClient: Cosmwasm_Wasm_V1beta1_QueryClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Cosmwasm_Wasm_V1beta1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the cosmwasm.wasm.v1beta1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Cosmwasm_Wasm_V1beta1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

